
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://www.kplus.vn/mykplus/account/getcaptcha');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Connection: keep-alive';
$headers[] = 'Sec-Ch-Ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\", \"Google Chrome\";v=\"99\"';
$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
$headers[] = 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36';
$headers[] = 'Sec-Ch-Ua-Platform: \"macOS\"';
$headers[] = 'Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8';
$headers[] = 'Sec-Fetch-Site: same-origin';
$headers[] = 'Sec-Fetch-Mode: no-cors';
$headers[] = 'Sec-Fetch-Dest: image';
$headers[] = 'Referer: https://www.kplus.vn/mykplus/account/registernew?lang=vi';
$headers[] = 'Accept-Language: vi-VN,vi;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6,en;q=0.5';
$headers[] = 'Cookie: current_site=1; Kplus.WebApp.Locale=vi-VN; sso_token=; ASP.NET_SessionId=zevszla3ee3vpjalabtadjww; __RequestVerificationToken_L215a3BsdXM1=Xwtq6h0iAnpW2i3-CPzgnhEBxaEZ0mnHfCTKX43LpSYdJNv_gjoPRPb0I5Xx915ujy8ytEtz4al0faV8dnViYsxW-YC00b2gG5qTUazDd3k1';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
echo 'Error:' . curl_error($ch);
}
curl_close($ch);
© 2017 - John C View on GitHub - dark mode


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://www.kplus.vn/mykplus/account/registernew?lang=vi');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "__RequestVerificationToken=AznGlTECsIMvgDcilO2osUjv34ymgrHF7Z9qfne6P8r9SscqhFzsvnFziS_jjnDjsxPV_MFwNOlBgYT7HgjvdJ3b6PT76ji5jaUD3fd5ey01&MobilePhone=0338931654&Email=&Password=0338931654&ConfirmPassword=0338931654&SmartCard=123456&SetTopBox=135328155460&CaptchaCode=H3JNZ&AgreeTermConditions=true&AgreeTermConditions=false");
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Connection: keep-alive';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Sec-Ch-Ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\", \"Google Chrome\";v=\"99\"';
$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
$headers[] = 'Sec-Ch-Ua-Platform: \"macOS\"';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'Origin: https://www.kplus.vn';
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
$headers[] = 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9';
$headers[] = 'Sec-Fetch-Site: same-origin';
$headers[] = 'Sec-Fetch-Mode: navigate';
$headers[] = 'Sec-Fetch-User: ?1';
$headers[] = 'Sec-Fetch-Dest: document';
$headers[] = 'Referer: https://www.kplus.vn/mykplus/account/registernew?lang=vi';
$headers[] = 'Accept-Language: vi-VN,vi;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6,en;q=0.5';
$headers[] = 'Cookie: current_site=1; Kplus.WebApp.Locale=vi-VN; sso_token=; ASP.NET_SessionId=zevszla3ee3vpjalabtadjww; __RequestVerificationToken_L215a3BsdXM1=Xwtq6h0iAnpW2i3-CPzgnhEBxaEZ0mnHfCTKX43LpSYdJNv_gjoPRPb0I5Xx915ujy8ytEtz4al0faV8dnViYsxW-YC00b2gG5qTUazDd3k1';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
echo 'Error:' . curl_error($ch);
}
curl_close($ch);