<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://owa.momo.vn/api/sync/QUERY_TRAN_HIS_MSG');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"user\":\"0966624292\",\"msgType\":\"QUERY_TRAN_HIS_MSG\",\"cmdId\":\"1595603654024000000\",\"lang\":\"vi\",\"channel\":\"APP\",\"time\":1595603654024,\"appVer\":\"21481\",\"appCode\":\"2.1.48\",\"deviceOS\":\"IOS\",\"result\":true,\"errorCode\":0,\"errorDesc\":\"\",\"extra\":{\"checkSum\":\"IhzBRk+uPwFMIAnEVfn6+kG/Jyz0+a6fmj8kQzEbm02VcgFg4/UMJFunZciomJxdYZpl+Z/PVOtb0U7BlfpKjVA+ggnEDwV0bgF5ZMEeCqI=\"},\"momoMsg\":{\"_class\":\"mservice.backend.entity.msg.QueryTranhisMsg\",\"begin\":1595403200585,\"end\":1595603654024}}");
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Host: owa.momo.vn:443';
$headers[] = 'Msgtype: QUERY_TRAN_HIS_MSG';
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiMDk2NjYyNDI5MiIsImltZWkiOiI1MzEyMkJFQy00NjEzLTQ4NzMtOTVGMS05MERBOTYzOEM0RUQiLCJCQU5LX0NPREUiOiIxMjM0NSIsIkJBTktfTkFNRSI6IlRNQ1AgTmdv4bqhaSBUaMawxqFuZyBWaeG7h3QgTmFtIiwiVkFMSURfV0FMTEVUX0NPTkZJUk0iOjMsIk1BUF9TQUNPTV9DQVJEIjowLCJOQU1FIjoiTkdVWUVOIFZBTiBET05HIiwiSURFTlRJRlkiOiJDT05GSVJNIiwicGluIjoiR0QxODJqbzBpMnc9IiwicGluX2VuY3J5cHQiOnRydWUsImlhdCI6MTU5NTYwMzY1MywiZXhwIjoxNTk1NjA5MDUzfQ.AJJNWwf37zN9zPrI735TwvrN5OZOw42wrE3f2b1eL6U';
$headers[] = 'Accept-Language: vi-vn';
$headers[] = 'Content-Type: application/json';
$headers[] = 'Userhash: b9e4ebb1e42de83f2a6589bf0b255540';
$headers[] = 'User-Agent: MoMoApp-Release/21481 CFNetwork/1126 Darwin/19.5.0';
$headers[] = 'Cookie: _ga=GA1.2.1034455276.1589351584';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$result = json_decode($result, true);
echo "<pre>";
print_r($result);
echo "</pre>";